### PR TITLE
Use new Hash syntax

### PR DESCRIPTION
**Pull request by okkez**
rubocop -a --only Style/HashSyntax lib test

### CODE REVIEW

**Comment by y-ken** [comment]
Thank you

**Comment by y-ken** [comment]
I'm afraid It need some improvements to support fluentd v0.14

**Comment by okkez** [comment]
It is easy to support Fluentd v0.14 API.
I will create new PR to support Fluentd v0.14 API. Could you tell me about improvements in the PR?

**Comment by y-ken** [comment]
It is happy to have message option.
For now, it need message key. I think better to have format in config.
Do you think Is it better to process with record-reformer?

```
<match foo.bar>
  @type twilio
  ..snip...
  message  Good news. ${record['name']} has made a order of ${record['item']} just now.
</match>
```

**Comment by okkez** [comment]
I think [filter_record_transformer](http://docs.fluentd.org/v0.14/articles/filter_record_transformer) is proper for this purpose.

```
<filter>
  @type record_transformer
  <record>
    message Good news. ${record['name']} has made a order of ${record['item']} just now.
  </record>
</filter>
```

I think it is very hard to keep placeholder feature.
So we should use Fluentd's built-in features and plugins.

**Comment by y-ken** [comment]
Exactly. Could you add a filter_record_transformer snippet in README?

**Comment by okkez** [comment]
Sure.

**Comment by y-ken** [comment]
Thank you.

**Pull request merged**
