### PR TITLE
Migrate to Fluentd v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by y-ken** [comment]
Thank you!

**Comment by okkez** [comment]
But I could not test this plugin in real world :bow:

**Comment by y-ken** [comment]
I will test in my environment.

**Comment by y-ken** [comment]
Thank you!

**Comment by y-ken** [comment]
@okkez 

Hi. It works well in english message.
But If I send multibyte message, It cause a error with following message in fluentd v0.14.14.
Do you know the solution of this multibytes issue?

```
echo '{"name":"太郎","item":"寿司"}' | /opt/td-agent/embedded/bin/fluent-cat notify.call
```

```
2017-06-02 21:43:20 +0900 [warn]: #0 dump an error event: error_class=Encoding::CompatibilityError error="incompatible character encodings: ASCII-8BIT and UTF-8" tag="notify.call" time=#<Fluent::EventTime:0x007f9752524e78 @sec=1496407400, @nsec=31985242> record={"name"=>"\u592A\u90CE", "item"=>"\u5BFF\u53F8"}
```

**Comment by okkez** [comment]
@y-ken 

Could you show me full trace?

**Comment by okkez** [comment]
I could not reproduce `Encoding::CompatibilityError` on my local machine with following configuration.

```
<source>
  @type forward
  @label @NOTIFY
</source>

<label @NOTIFY>
  <filter>
    @type record_transformer
    <record>
      message ${record["message"]} ${record["item"]}
    </record>
  </filter>
  <match dummy.log>
    # @type stdout
    @type twilio
    account_sid     sid
    auth_token      token

    from_number +8112345678
  </match>
</label>
```

**Comment by y-ken** [comment]
There are some case which have troubled with Encoding::CompatibilityError.
http://inokara.hateblo.jp/entry/2015/06/24/010004
https://blue21neo.blogspot.jp/2016/03/centos6fluentd-filtergrep.html

Could you try following code contains japanese?

````
<source>
  @type forward
  @label @NOTIFY
</source>

<label @NOTIFY>
  <filter>
    @type record_transformer
    <record>
      message こんにちは. ${record["name"]} has made a order of ${record["item"]} just now.
    </record>
  </filter>
  <match dummy.log>
    # @type stdout
    @type twilio
    account_sid     sid
    auth_token      token

    from_number +8112345678
  </match>
</label>
```

**Comment by y-ken** [comment]
I have send you a api key for twilio for now.
Thank you.

**Comment by okkez** [comment]
Related to https://github.com/fluent/fluentd/pull/1477.
And this is caused by filter_record_transformer's bug.
We should consider encoding in fluent.conf but [this line](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/filter_record_transformer.rb#L121) does not consider encoding.

**Comment by y-ken** [comment]
Hmm, It is so deep problem. I'm not sure why internal encodings are ASCII-8BIT.

**Comment by okkez** [comment]
Fluentd reads data from external via lots of sources such as local file, network and etc.
So Fluentd cannot assume encoding of external sources.

**Comment by y-ken** [comment]
Thank you for suggestion.
I guess filter_record_transformer's encoding problem are caused filter-grep too.

**Comment by y-ken** [comment]
Thank you. @okkez 
I'll check it again after released new fluentd gem.

**Comment by y-ken** [comment]
released v0.1.0 just now!

**Pull request merged**
